# Generated by Django 5.2.5 on 2025-08-30 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_remove_telegramuser_verification_data'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_reference', models.CharField(max_length=255, unique=True)),
                ('bot_id', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='UAH', max_length=3)),
                ('payment_status', models.CharField(choices=[('NEW', 'New'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('REFUNDED', 'Refunded'), ('EXPIRED', 'Expired')], default='NEW', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('auth_code', models.CharField(blank=True, max_length=50, null=True)),
                ('card_pan', models.CharField(blank=True, max_length=20, null=True)),
                ('card_type', models.CharField(blank=True, max_length=50, null=True)),
                ('issuer_bank', models.CharField(blank=True, max_length=100, null=True)),
                ('issuer_country', models.CharField(blank=True, max_length=3, null=True)),
                ('payment_system', models.CharField(blank=True, max_length=50, null=True)),
                ('reason_code', models.CharField(blank=True, max_length=10, null=True)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rrn', models.CharField(blank=True, max_length=50, null=True)),
                ('approval_code', models.CharField(blank=True, max_length=50, null=True)),
                ('terminal', models.CharField(blank=True, max_length=50, null=True)),
                ('rec_token', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('raw_request_payload', models.JSONField(blank=True, null=True)),
                ('raw_response_payload', models.JSONField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.plan')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.telegramuser')),
            ],
            options={
                'db_table': 'payment_invoices',
            },
        ),
        migrations.CreateModel(
            name='VerifiedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.IntegerField()),
                ('first_payment_date', models.DateTimeField()),
                ('card_masked', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_system', models.CharField(blank=True, max_length=50, null=True)),
                ('issuer_bank', models.CharField(blank=True, max_length=100, null=True)),
                ('successful_payments_count', models.IntegerField(default=1)),
                ('total_amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('last_payment_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.telegramuser')),
            ],
            options={
                'db_table': 'verified_users',
                'unique_together': {('user', 'bot_id')},
            },
        ),
    ]
