# Generated by Django 5.2.5 on 2025-08-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='reason_code',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
