# Generated by Django 5.2.5 on 2025-09-11 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bot_domain_name_bot_last_heartbeat_bot_log_path_and_more'),
        ('payments', '0002_alter_invoice_reason_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_account', models.CharField(max_length=255)),
                ('secret_key', models.CharField(max_length=255)),
                ('pay_url', models.URLField(default='https://secure.wayforpay.com/pay')),
                ('api_url', models.URLField(default='https://api.wayforpay.com/api')),
                ('verify_signature', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_config', to='core.bot')),
            ],
            options={
                'db_table': 'merchant_configs',
            },
        ),
    ]
