# Generated by Django 5.2.5 on 2025-09-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_merchantconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantconfig',
            name='django_api_base',
            field=models.URLField(default='https://dev.astrocryptovoyager.com/api/payments/wayforpay', help_text='URL Django API для создания инвойсов (НЕ WayForPay API!)'),
        ),
    ]
