# Generated by Django 5.2.5 on 2025-10-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_merchantconfig_django_api_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantconfig',
            name='django_api_base',
            field=models.URLField(default='https://dev.profilinggroup.com/api/payments/wayforpay', help_text='URL Django API для создания инвойсов (НЕ WayForPay API!)'),
        ),
    ]
