# Generated by Django 5.2.5 on 2025-10-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_merchantconfig_django_api_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_recurrent_manual',
            field=models.BooleanField(default=False, help_text='Для ручной активации: подписка до 9999-12-31', verbose_name='Рекуррентная (бессрочная)'),
        ),
    ]
