# Generated by Django 5.2.5 on 2025-10-02 20:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_logdummy'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadBotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_email', models.EmailField(blank=True, help_text='Email для отправки уведомлений о новых заявках', max_length=255, null=True, validators=[django.core.validators.EmailValidator()])),
                ('admin_user_id', models.BigIntegerField(blank=True, help_text='Telegram User ID администратора для уведомлений', null=True)),
                ('welcome_text', models.TextField(default='Привет! 👋\n\nЯ помогу вам оставить заявку.\nВведите ОДНИМ СООБЩЕНИЕМ ваше имя, вопрос или пожелание, будь ласка', help_text='Приветственное сообщение при /start')),
                ('phone_request_text', models.TextField(default='Введите номер телефону, за яким можна зв\'язатися з Вами, будь ласка 📞\n\nНомер у форматі +380... або натисніть нижче кнопку "Поділитися номером"', help_text='Текст запроса телефона')),
                ('email_request_text', models.TextField(default="Vlad, це правильний номер телефону для зв'язку з Вами?\n\nПеревірте, будь ласка", help_text='Текст валидации телефона и запроса email')),
                ('comment_request_text', models.TextField(default='Vlad, останній крок 😊\n\nБажаєте залишити побажання, коментар чи запитання, будь ласка', help_text='Текст запроса комментария')),
                ('success_text', models.TextField(default='Vlad, супер, отримали Вашу заявку 💪👍\n\nНайближчим часом з Вами зв\'яжеться координатор і відповість на всі запитання, будьте на зв\'язку😊\n\nЯкщо у Вас буде питання, натисніть кнопку "Є питання" і напишіть його 👇', help_text='Текст успешного сохранения заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead_config', to='core.bot', verbose_name='Бот')),
            ],
            options={
                'verbose_name': 'Настройки Lead Bot',
                'verbose_name_plural': 'Настройки Lead Bot',
                'db_table': 'lead_bot_configs',
                'permissions': [('can_view_leads', 'Может просматривать заявки'), ('can_manage_lead_bot', 'Может управлять настройками Lead Bot')],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Номер должен быть в формате +380XXXXXXXXX', regex='^\\+380\\d{9}$')], verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий/Вопрос')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Email отправлен')),
                ('telegram_sent', models.BooleanField(default=False, verbose_name='Telegram уведомление отправлено')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='core.bot', verbose_name='Бот')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='core.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'leads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='leads_created_f50ac1_idx'), models.Index(fields=['status'], name='leads_status_94f025_idx'), models.Index(fields=['bot', '-created_at'], name='leads_bot_id_a6dcc2_idx')],
            },
        ),
    ]
