# Generated by Django 5.2.5 on 2025-08-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_telegramuser_verification_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.PositiveIntegerField(help_text='Внутренний ID бота (совпадает с Plan.bot_id)', unique=True)),
                ('title', models.CharField(blank=True, help_text='Человеческое имя бота', max_length=255)),
                ('username', models.CharField(blank=True, help_text='@username в Telegram', max_length=255)),
                ('token', models.CharField(blank=True, help_text='HTTP API токен бота (храним аккуратно)', max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bots',
                'indexes': [models.Index(fields=['bot_id', 'is_enabled'], name='bots_bot_id_922fca_idx')],
            },
        ),
    ]
