# Generated by Django 5.2.5 on 2025-09-11 12:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='domain_name',
            field=models.CharField(blank=True, help_text='Доменное имя для вебхука', max_length=255),
        ),
        migrations.AddField(
            model_name='bot',
            name='last_heartbeat',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bot',
            name='log_path',
            field=models.CharField(blank=True, help_text='Путь к лог-файлу', max_length=255),
        ),
        migrations.AddField(
            model_name='bot',
            name='path',
            field=models.CharField(blank=True, help_text='Рабочая директория скрипта', max_length=255),
        ),
        migrations.AddField(
            model_name='bot',
            name='port',
            field=models.PositiveIntegerField(blank=True, help_text='Порт для вебхука (например, 8101)', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('failed', 'Failed')], default='stopped', max_length=20),
        ),
    ]
