# Generated by Django 5.2.5 on 2025-09-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bot_domain_name_bot_last_heartbeat_bot_log_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogDummy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Django Logs',
                'verbose_name_plural': 'Django Logs',
                'managed': False,
            },
        ),
    ]
