# Generated by Django 5.2.5 on 2025-09-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentNotification',
            fields=[
                ('order_reference', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Уведомление об успехе оплаты',
                'verbose_name_plural': 'Уведомления об успехе оплаты',
                'db_table': 'bot_payment_notifications',
            },
        ),
        migrations.CreateModel(
            name='ExpiryNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.IntegerField()),
                ('tg_user_id', models.BigIntegerField()),
                ('expires_on', models.DateField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Напоминание об окончании подписки',
                'verbose_name_plural': 'Напоминания об окончании подписки',
                'db_table': 'bot_expiry_notifications',
                'indexes': [models.Index(fields=['bot_id', 'expires_on'], name='bot_expiry__bot_id_a7df40_idx'), models.Index(fields=['tg_user_id'], name='bot_expiry__tg_user_ed5aad_idx')],
                'unique_together': {('bot_id', 'tg_user_id', 'expires_on')},
            },
        ),
    ]
