# Generated by Django 5.2.5 on 2025-08-30 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.IntegerField(help_text='ID бота')),
                ('name', models.CharField(help_text='Название плана', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена', max_digits=10)),
                ('currency', models.CharField(default='UAH', max_length=3)),
                ('duration_days', models.PositiveIntegerField(default=30, help_text='Длительность в днях')),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscription_plans',
                'indexes': [models.Index(fields=['bot_id', 'enabled'], name='subscriptio_bot_id_b2f983_idx')],
                'unique_together': {('bot_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.IntegerField(help_text='ID бота')),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('expired', 'Expired'), ('canceled', 'Canceled')], default='active', max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('card_token', models.CharField(blank=True, max_length=255, null=True)),
                ('card_masked', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.telegramuser')),
            ],
            options={
                'db_table': 'subscriptions',
                'indexes': [models.Index(fields=['bot_id', 'user', 'status'], name='subscriptio_bot_id_75a852_idx'), models.Index(fields=['expires_at'], name='subscriptio_expires_af5d7e_idx')],
                'unique_together': {('user', 'plan', 'bot_id')},
            },
        ),
    ]
