# Generated by Django 5.2.5 on 2025-09-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_logdummy'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Сумма платежа', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='order_reference',
            field=models.CharField(blank=True, help_text='Ссылка на заказ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='recurrent_date_begin',
            field=models.DateField(blank=True, help_text='Начало периода рекуррента', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='recurrent_date_end',
            field=models.DateField(blank=True, help_text='Конец периода рекуррента', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='recurrent_mode',
            field=models.CharField(blank=True, help_text='Режим: weekly/monthly', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='recurrent_next_payment',
            field=models.DateField(blank=True, help_text='Дата следующего автоплатежа', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='recurrent_status',
            field=models.CharField(blank=True, help_text='Статус автоплатежей: Active/Paused/Canceled', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='reminder_failed_attempts',
            field=models.IntegerField(default=0, help_text='Неудачные попытки оплаты'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='Когда было последнее напоминание', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='reminder_sent_count',
            field=models.IntegerField(default=0, help_text='Количество отправленных напоминаний'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='ID транзакции', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='card_masked',
            field=models.CharField(blank=True, help_text='Замаскированный номер карты', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='card_token',
            field=models.CharField(blank=True, help_text='Токен карты для автоплатежей', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['recurrent_next_payment'], name='subscriptio_recurre_2c1341_idx'),
        ),
    ]
